### ISSUE TITLE
Screen flickers whenever using the widget in Salesforce

### ISSUE THREAD

**Issue by byronsanchez** [ringcentral-tutorials/ringcentral-embeddable-demos#48]
The widget is flickering in Salesforce.

I found that there was an interval set in `RCPhone.vfp`:

https://github.com/ringcentral-tutorials/ringcentral-web-widget-demos/blob/eb60f258e010dd236bb8f5b05ea8344374ef287b/docs/salesforce_lightning_more/code/RCPhone.vfp#L104-L110

Unfortunately, removing the interval introduces a screen disappearing bug, as per 1343a45.

I'm wondering if there's anything we can do to fix the screen disappearing bug and not have the screen flicker.

When I disable the interval and monitor the Chrome Developer Tools window for errors that occur once the screen disappears, I get the following:

```
Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-5a9d6b09-b607-b83e-4866-c8fe1edf9501' chrome-extension: 'unsafe-inline' 'unsafe-eval' https://sfdc.azureedge.net *.na50.visual.force.com 'unsafe-eval' https://ssl.gstatic.com/accessibility/". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

I also saw:

```
Uncaught DOMException: Blocked a frame with origin "https://ringcentral.github.io" from accessing a cross-origin frame.
    at window_blur (chrome-extension://ddaloccgjfibfpkalenodgehlhkgoahe/jslib/nuanria.FrameConnector.js:338:18)
```

**Comment by tylerlong** [comment]
Check this tutorial: https://github.com/ringcentral/ringcentral-web-widget/issues/7

**Comment by grokify** [comment]
Try upgrading to Chrome 65 and deleting the interval. The Chrome iframe blank page bug was fixed in 65 for me so the interval is no longer needed.

Here's my testing experience:

| Chrome Version | iframe blank page bug | interval needed |
| -------------------|---------------------------|-------------------|
| `65.0.3325.146 (Official Build) (64-bit)` | no | no |
| `64.0.3282.186 (Official Build) (64-bit)` | yes | yes |
| `63.0.3239.84 (Official Build) (64-bit)` | yes | yes |

**Comment by grokify** [comment]
Closing due to lack of response.
